# Base image
FROM python:3.11-alpine

RUN pip install --upgrade pip

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install system dependencies
RUN apk update

# Create directory for the application code
RUN mkdir /app

# Set working directory
WORKDIR /app

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY ./LisciTask .

# Migrate app
RUN python manage.py migrate --no-input

# Create super user
RUN python manage.py createsuperuser --noinput \
    --username=admin \
    --email=admin@lisci.com \
    --password=admin

# Run the application
EXPOSE 8000
CMD python manage.py runserver 0.0.0.0:8000